language: java

sudo: false

jdk:
- openjdk8

branches:
  only:
  - master

env:
  - GPG_KEY="$GPG_KEY"
  - GPG_PASS="$GPG_PASS"

cache:
  directories:
  - '$HOME/.m2/repository'

script:
- "mvn clean compile"